### ISSUE TITLE
estou com problema que não responde em grupo

### ISSUE THREAD

**Issue by yumizzzy** [HugoLibanori/masterbot-whatsapp#1]
opa, eu uso ubuntu server, aparentemente rodou, mas nao responde em grupo e aparece undefined do lado do nome no menu, exemplo:

undefinedreportar
![Screenshot_20240224-151950_WhatsApp](https://github.com/HugoLibanori/masterbot-whatsapp/assets/82894998/4028f4a3-98e5-401d-abbf-e6a4645c156f)

**Comment by HugoLibanori** [comment]
ele criou o arquivo .env?

**Comment by HugoLibanori** [comment]
eu fiz uma correção nos prefix acredito que agora não va aparecer undefined de um git pull no seu projeto

**Comment by yumizzzy** [comment]
> eu fiz uma correção nos prefix acredito que agora não va aparecer undefined de um git pull no seu projeto
