### ISSUE TITLE
Ótimo trabalho com o bot

### ISSUE THREAD

**Issue by victorsouzaleal** [HugoLibanori/masterbot-whatsapp#2]
Bom ver que você continuou a atualizar o seu e até teve o trampo de passar para Typescript 😃

**Comment by HugoLibanori** [comment]
salve mano, sim peguei seu projeto com outra lib e joguei para typescript. mais pra treino mesmo ainda estou caminhando...kkkkk... desculpa não ter falado com vc, pois peguei seu projeto, mas como vc tinha descontinuado não quis encher o seu saco. ai peguei a base e criei esse projetinho. 🤩🤙

**Comment by victorsouzaleal** [comment]
Relaxa po, continua que ta maneiro kkkkkk tente mais ser organizado que a minha bagunça 😆
